### ISSUE TITLE
Can't construct a java object for !starter; exception=Invalid tag: !starter

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-booster-catalog-service#26]
The following error is displayed in the logs when I execute the following code:

```java
    public static void main(String[] args) throws Exception {
        RhoarBoosterCatalogService catalogService = new RhoarBoosterCatalogService.Builder()
                .catalogRepository("https://github.com/quintesse/launcher-booster-catalog")
                .catalogRef("staging")
                .build();
        catalogService.index().get();
        System.out.println(catalogService.getMissions());
    }
```

```java
SEVERE: Error while reading /tmp/booster-catalog3351053739972783282/crud/common.yaml
Can't construct a java object for !starter; exception=Invalid tag: !starter
 in 'reader', line 2, column 11:
      runsOn: !starter
              ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:313)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462)
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443)
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:519)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:462)
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:183)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:443)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:136)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:484)
	at io.openshift.booster.catalog.AbstractBoosterCatalogService.readBooster(AbstractBoosterCatalogService.java:373)
	at io.openshift.booster.catalog.AbstractBoosterCatalogService.indexPath(AbstractBoosterCatalogService.java:288)
	at io.openshift.booster.catalog.AbstractBoosterCatalogService.lambda$indexPath$7(AbstractBoosterCatalogService.java:298)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.openshift.booster.catalog.AbstractBoosterCatalogService.indexPath(AbstractBoosterCatalogService.java:298)
	at io.openshift.booster.catalog.AbstractBoosterCatalogService.indexBoosters(AbstractBoosterCatalogService.java:257)
	at io.openshift.booster.catalog.rhoar.RhoarBoosterCatalogService.indexBoosters(RhoarBoosterCatalogService.java:120)
	at io.openshift.booster.catalog.AbstractBoosterCatalogService.doIndex(AbstractBoosterCatalogService.java:248)
	at io.openshift.booster.catalog.AbstractBoosterCatalogService.lambda$index$0(AbstractBoosterCatalogService.java:117)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: org.yaml.snakeyaml.error.YAMLException: Invalid tag: !starter
	at org.yaml.snakeyaml.nodes.Tag.getClassName(Tag.java:112)
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:637)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:298)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:308)
	... 36 more```

**Comment by quintesse** [comment]
You already fixed that yourself, right @gastaldi ?

**Comment by gastaldi** [comment]
Yes. We just need to tell the catalog maintainers to use double quotes when declaring values like this. Closing
