### ISSUE TITLE
Dirty NPE in NativeGitBoosterCatalogPathProvider.createBoosterContentPath

### ISSUE THREAD

**Issue by ia3andy** [fabric8-launcher/launcher-booster-catalog-service#46]
the code in `NativeGitBoosterCatalogPathProvider.createBoosterContentPath` can be dangerous
`booster.getGitRepo()` and `booster.getGitRef()` are both `@Nullable` and can lead to a dirty ProcessBuilder NPE.

```
Caused by: java.lang.NullPointerException
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
    at io.fabric8.launcher.booster.catalog.spi.NativeGitBoosterCatalogPathProvider.createBoosterContentPath(NativeGitBoosterCatalogPathProvider.java:89)
    at io.fabric8.launcher.booster.catalog.AbstractBoosterCatalogService.lambda$fetchBoosterContent$4(AbstractBoosterCatalogService.java:194)
    ... 9 more
```

**Comment by ia3andy** [comment]
it seems to happen with an invalid/outdated catalog
