### ISSUE TITLE
Error with script filter

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-booster-catalog-service#96]
@quintesse BTW I am afraid that this feature is broken with the `booster-catalog-service` conversion to Kotlin. Here is a sample code that reproduces the issue I am seeing: 
```java
        Predicate<RhoarBooster> filter = BoosterPredicates.withScriptFilter("booster.mission.id == 'rest-http'");
        RhoarBoosterCatalogService service = new RhoarBoosterCatalogService.Builder()
                .filter(filter) // REMOVE THIS LINE AND IT RUNS
                .build();
        service.index().get();
        for (RhoarBooster booster : service.getBoosters()) {
            System.out.println("TESTING " + booster);
            System.out.println(filter.test(booster));
        }
```

Fails with: 
```java
Caused by: <eval>:1 TypeError: Cannot get property "id" of null
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkNull(NashornBottomLinker.java:183)
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:66)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:421)
```

Remove the `filter()` call and the program runs

_Originally posted by @gastaldi in https://github.com/fabric8-launcher/launcher-planning/issues/207#issuecomment-472691510_

**Comment by quintesse** [comment]
@gastaldi I don't think this has anything to do with the conversion to Kotlin, I just think this particular situation was never tested. But it'd fixed now :-)
